#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
	/usr/sbin/camera-network-leds apply >/dev/null 2>&1
	procd_open_instance
	procd_set_param command /usr/sbin/camera-network-monitor
	procd_set_param respawn 5 5 0
	procd_close_instance
}
